### ISSUE TITLE
Extension taken down

### ISSUE THREAD

**Issue by paulirish** [axenol/drive-quick-search#12]
It was removed from the chrome web store. https://chrome.google.com/webstore/detail/google-drive-quick-search/ddebdlfmldojeofgkeocjdkloocegmae

looks like a "trademark" issue. `Abuse type:TRADEMARK_THIRD_PARTY`

Probably something to do with 
* https://developer.chrome.com/webstore/branding
* https://developer.chrome.com/webstore/program_policies#content_policies

@axenol you see where we'd be violating?

**Comment by axenol** [comment]
Yes, we need a new icon. I got a notice about it. I don't know what to do
about the logo though.

**Comment by paulirish** [comment]
I could probably get us written permission from Google. :)

You're not one for designing logos are  you? :)

I'm thinking some magnifying class + drive icon + speed

**Comment by axenol** [comment]
Well I made the current logo which isn't really good or something :). And
that permission would be really cool. I think we shouldn't include the
drive icon at all without a permission.

**Comment by axenol** [comment]
Soo what are we going to do about this?

**Comment by paulirish** [comment]
we need a new logo!​

**Comment by paulirish** [comment]
how about http://thumb101.shutterstock.com/thumb_large/657868/197017343/stock-vector-search-icon-with-modern-triangle-pattern-197017343.jpg but with google drive colors

**Comment by axenol** [comment]
With 3 colors, wouldn't that be too colorful? I mean I can't imagine it
looking good. I will ask some friends to see what they can come up with too.

**Comment by paulirish** [comment]
![image](https://cloud.githubusercontent.com/assets/39191/7245235/8f1c7a6a-e79c-11e4-9199-b27def3d8799.png)

made in about 3 min with http://williamngan.github.io/kubist/ and the real logo ([google-drive-icon](https://cloud.githubusercontent.com/assets/39191/7245245/9f856b32-e79c-11e4-8ed5-92871f66ea21.jpg))

i think we could do something quite similar. 

i gotta prep for a talk i'm giving tomorrow but lets noodle around this idea

**Comment by axenol** [comment]
I'll be handling this soon, hopefully. How about the written permission thing? We can even maybe get ourselves a cool logo after that :)

**Comment by evanhammer** [comment]
What's the status on this? I've been using Google Drive Quick Search extensively and was sad to see it go. Thanks for putting together an awesome tool!

**Comment by axenol** [comment]
Well, this is the last week of college and I really have no time to take
care of this. As soon as I have a new logo I will reupload it and also
start working on the extension. Meanwhile you can pull the repo and install
it as a unpacked extension from chrome. Thanks for your attention :)

**Comment by evanhammer** [comment]
I can create a new logo. And then your call if you want to use it. What are the requirements? Name, colors, size? Any logos you like?

**Comment by evanhammer** [comment]
And as a follow up, what if we brand it "Quick Search for Google Drive"?

**Comment by axenol** [comment]
I have nothing in mind. Just something representing Drive (maybe its colors) and maybe a magnifier glass or something like that. I could use anything right now so I would be more than happy if you go ahead and give it a shot.

**Comment by axenol** [comment]
That brand also sounds better, I guess, in terms of the Web Store rules.

**Comment by evanhammer** [comment]
How's this? I can do a pull request to update the icons and change all instances of "Google Drive Quick Search" to "Quick Search for Google Drive".

![quick-search-icon-256](https://cloud.githubusercontent.com/assets/1487421/7636322/920ff760-fa34-11e4-899c-7fff39110066.png)

**Comment by axenol** [comment]
I think you tried to use similar colors but the colors can be exact same as Google Drive's colors other than that we can use this until we get a better one. You can do the pull request as you mentioned but please do it with the updated colors.

**Comment by axenol** [comment]
Or just send me the icon because I don't want to use the code from github. This is a reimplementation and has its issues. So that I can update the icon and branding.

**Comment by paulirish** [comment]
If you don't want to publish what's on master then we should use a branch.

**Comment by axenol** [comment]
Well yes but I was thinking I should rewrite it from the beginning and the
old version is just not going to be updated at all. So I don't really think
we need it.

**Comment by evanhammer** [comment]
Here's the exact colors version. I think the darkened colors make the white search icon look better. Anything else you need from me?

![quick-search-icon-colors](https://cloud.githubusercontent.com/assets/1487421/7659762/6fa7fd10-fb12-11e4-9c7f-5edba42486c8.png)

**Comment by evanhammer** [comment]
one with some shadow:
![quick-search-icon-shadow](https://cloud.githubusercontent.com/assets/1487421/7662639/ec9072ac-fb2c-11e4-9e4c-bbea226c3972.png)

**Comment by axenol** [comment]
This looks much better with shadow. I will try to update the web store
entry as soon as possible and we will see what's going to happen.

**Comment by evanhammer** [comment]
heart. thanks!

**Comment by evanhammer** [comment]
Has Google sent you any response?

**Comment by axenol** [comment]
Couldn't update it yet, I am out of town right now and will do as soon as possible

**Comment by axenol** [comment]
Just submitted this with the new icon and the new brand (Quick Search for Google Drive). Now it's marked for manual review. Maybe Paul you can speed up the process a bit :)

**Comment by evanhammer** [comment]
Looks like it's back up and running. Should we close this out?

**Comment by axenol** [comment]
Yeah cool!

**Comment by paulirish** [comment]
Added the logo to the repo here f7c252616390a5fdad7b0779a250d16a239bd2e9
