### ISSUE TITLE
Ahmet too busy.

### ISSUE THREAD

**Issue by axenol** [axenol/drive-quick-search#14]
Last 4 weeks of school, I am really busy right now. Planning to review and improve this extension once I am done with the school. As of right now, sorry Paul, you are on your own. It is saddening to see you opening so many issues :)

**Comment by paulirish** [comment]
all good. appreciate the time you can put in. 

I might publish the extension on CWS separately as we can't share yours easily.

**Comment by axenol** [comment]
No need. I can add you to the developers group and you will have full
access to it in the developer dashboard.

**Comment by paulirish** [comment]
with oauth 2 we also need to register APIs with the same google account.

i'm gonna stay forked for a moment while this oauth shit gets sorted out.
​

**Comment by axenol** [comment]
I can add you to the project owners from developer console too for the oauth stuff. I actually did now, but for your google email, if you prefer any other email I could do that too.

**Comment by paulirish** [comment]
google email for both wfm.​

**Comment by axenol** [comment]
I can't add a new group for some reason, probably because I have extensions taken down. We need to fix this somehow.

**Comment by axenol** [comment]
We can also add a whole new extension but that wouldn't make sense as I don't want to lose the already existing user base.

**Comment by axenol** [comment]
Closing this and creating a new one.
