### ISSUE TITLE
oauth v1 is broken

### ISSUE THREAD

**Issue by paulirish** [axenol/drive-quick-search#15]
and we're on it.

there was a warning for a while and as of today ( it seems ) it is dead. so dead.  

need to move to v2.

**Comment by paulirish** [comment]
@beaufortfrancois you can probably help us here.

http://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/extensions/docs/examples/extensions/oauth_contacts/ is dead right?

can extensions use the chrome.identity API? if so then it feels like your pattern from https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/gdrive would be ace, yeah?

**Comment by paulirish** [comment]
some WIP work in https://github.com/axenol/drive-quick-search/compare/master...oauth2
definitely not working yet.

**Comment by beaufortfrancois** [comment]
Extensions can use the `chrome.identity` API (https://developer.chrome.com/extensions/identity) to get OAuth2 Acccess Tokens.
I've created myself long time ago an extension called Omnidrive which adds support to the omnibox to search in Google Drive with the `chrome.identity` API.

See https://chrome.google.com/webstore/detail/omnidrive/gpnikbcifngfgfcgcgfahidojdpklfia and source code at https://github.com/beaufortfrancois/omnidrive-chrome-extension

**Comment by paulirish** [comment]
Oh boy. :)
Glad I tagged you. That's the same thing. I'm interested in merging efforts.

**Comment by paulirish** [comment]
Ah. Looked at your source. It's kept nice and simple. :)
Are you interested in client side caching?

**Comment by beaufortfrancois** [comment]
Ooooh! I didn't know ttps://www.googleapis.com/drive/v2/changes exists. 
Quick Drive Search seems better now.

Do you want me to submit a PR to convert the extension to use `chrome.identity` API?

**Comment by beaufortfrancois** [comment]
See https://github.com/axenol/drive-quick-search/pull/17
