### ISSUE TITLE
Upgrade to OAuth 2 as OAuth 1 is no longer supported

### ISSUE THREAD

**Issue by evanhammer** [axenol/drive-quick-search#19]
When I try to re-authenticate, Google brings me to a page saying that OAuth 1 is no longer supported and that we should be using OAuth 2.0. Has anybody else come across this issue?

https://support.google.com/a/answer/6224347?p=oauth&rd=1

**Comment by axenol** [comment]
Yes. This is fixed in the new code but we need the integrate the new system into old code or just deploy the new code to web store.

**Comment by evanhammer** [comment]
How does the new code and old code and complete rewrite figure in together? Where is the new code and what do we need to do to integrate it with the old code?

**Comment by axenol** [comment]
I'll create a new branch with the old code and update it to use new oauth.

**Comment by evanhammer** [comment]
Any update here? Anything I can do to help?

**Comment by axenol** [comment]
I created a new branch called 'release' and updated it to use OAuth2. Also published it on the CWS now, so it should be up soon. I'd be happy if you can test it from the store.

**Comment by evanhammer** [comment]
It's working for me. Thanks!
