### ISSUE TITLE
caching: display notification

### ISSUE THREAD

**Issue by paulirish** [axenol/drive-quick-search#8]
While we're pulling down all the items we should show an omnibox entry that says we're busy. 

"Google Drive Quick Search: We're currently indexing your drive files. Bucket 12 complete…"

**Comment by paulirish** [comment]
Can you add me as a repo collab?

**Comment by axenol** [comment]
Just did. Sorry I am not able to work on this. School is keeping me busy. Gotta graduate to start working at Google :)
